apiVersion: v1
kind: Service
metadata:
  labels:
    name: hbase-box-service
  name: hbase-box-service
spec:
  ports:
  - name: "2222"
    port: 2181
    nodePort: 31222
  - name: "60010"
    port: 60010
    nodePort: 31010
  - name: "60000"
    port: 60000
    nodePort: 31000
  - name: "60020"
    port: 60020
    nodePort: 31020
  - name: "60030"
    port: 60030
    nodePort: 31030
  - name: "9090"
    port: 9090
    nodePort: 31090
  selector:
    name: hbase-box
status:
  loadBalancer: {}
